### ISSUE TITLE
abstract media handlers

### ISSUE THREAD

**Issue by yudukikun5120** [mkobayashime/video-stream-shortcuts#142]
Thanks to the introduction of TSC, we can use the abstract classes which support the imposition of restrictions (e.g. implementation enforcement of class methods) on each media handler such as `daznHandler`. The inheritance using an abstract class brings obvious advantages when you want to add support for a certain streaming service in reducing the codes to be written.

## Tasks
- [ ] turn`primeVideo.ts` and `ted.ts` into classes
- [ ] create the abstract class for handling media
- [ ] have the four handlers to be inherited from the abstract class

**Comment by yudukikun5120** [comment]
I'd support Tver after this issue is resolved.

**Comment by yudukikun5120** [comment]
@mkobayashime If any impressions or reasons opposing this plan you have, please tell me about them.
